version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: presentations
    ports:
      - "8080:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./src/db/migrations/migration.sql:/docker-entrypoint-initdb.d/migration.sql  # SQL dosyasını kopyala
