version: '4'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: presentations
    ports:
      - "8080:8080"
    volumes:
      - ./db_data:/var/lib/postgresql/data
